from ultralytics import YOLO

# Load the YOLO model
model = YOLO("yolov8n.pt")

# Update the model's class names
data_set = {
    "0": "Die Person",
    "1": "Das Fahrrad",
    "2": "Das Auto",
    "3": "Das Motorrad",
    "4": "Das Flugzeug",
    "5": "Der Bus",
    "6": "Der Zug",
    "7": "Der LKW",
    "8": "Das Boot",
    "9": "Die Ampel",
    "10": "Der Hydrant",
    "11": "Das Stoppschild",
    "12": "Die Parkuhr",
    "13": "Die Bank",
    "14": "Der Vogel",
    "15": "Die Katze",
    "16": "Der Hund",
    "17": "Das Pferd",
    "18": "Das Schaf",
    "19": "Die Kuh",
    "20": "Der Elefant",
    "21": "Der Bär",
    "22": "Das Zebra",
    "23": "Die Giraffe",
    "24": "Der Rucksack",
    "25": "Der Schirm",
    "26": "Die Handtasche",
    "27": "Die Krawatte",
    "28": "Der Koffer",
    "29": "Der Frisbee",
    "30": "Die Skier",
    "31": "Das Snowboard",
    "32": "Der Sportball",
    "33": "Der Drachen",
    "34": "Der Baseballschläger",
    "35": "Der Baseballhandschuh",
    "36": "Das Skateboard",
    "37": "Das Surfbrett",
    "38": "Der Tennisschläger",
    "39": "Die Flasche",
    "40": "Das Weinglas",
    "41": "Die Tasse",
    "42": "Die Gabel",
    "43": "Das Messer",
    "44": "Der Löffel",
    "45": "Die Schüssel",
    "46": "Die Banane",
    "47": "Der Apfel",
    "48": "Das Sandwich",
    "49": "Die Orange",
    "50": "Der Brokkoli",
    "51": "Die Karotte",
    "52": "Der Hotdog",
    "53": "Die Pizza",
    "54": "Der Donut",
    "55": "Der Kuchen",
    "56": "Der Stuhl",
    "57": "Die Couch",
    "58": "Die Topfpflanze",
    "59": "Das Bett",
    "60": "Der Esstisch",
    "61": "Die Toilette",
    "62": "Der Fernseher",
    "63": "Der Laptop",
    "64": "Die Maus",
    "65": "Die Fernbedienung",
    "66": "Die Tastatur",
    "67": "Das Handy",
    "68": "Die Mikrowelle",
    "69": "Der Ofen",
    "70": "Der Toaster",
    "71": "Das Waschbecken",
    "72": "Der Kühlschrank",
    "73": "Das Buch",
    "74": "Die Uhr",
    "75": "Die Vase",
    "76": "Die Schere",
    "77": "Der Teddybär",
    "78": "Der Haartrockner",
    "79": "Die Zahnbürste"
}


model.model.names.update(data_set)

# Run inference on the webcam feed
results = model(source=0, show=True, conf=0.6, verbose=False)  # Suppress default logs
